### ISSUE TITLE
rarity

### ISSUE THREAD

**Issue by AndyJ01** [tewky/dvcalculator#1]
I tried to send this as an email but it said tewky57@protonmail.com doesn't exist.

Hey, I emailed you awhile back about your DV calculator and specifically the "rare" stat (gen 1). Well I finally got some time and patience to look into the math behind it, and I've come up with something that would accurately represent rarity, including HP. I looked at your code a bit but I'm not good enough with JavaScript yet to attempt to change and test it myself, so I figured I'd tell you about it.

Basically I calculated every way in which each DV total could theoretically happen. These occurrences are all equally likely (in theory), so it was just a matter of sorting the 65536 possibilities into groups with totals 0-75. Then I assigned rounded harmonic fractions to the groups much like you have. I noticed that the calculator will say a fraction like "1/4" for some pretty bad stats, taken to mean that only 1 in 4 Pokémon would have at least as good DVs, while the reality is much higher. Actually, the bottom 3/8ths or so of "genomes" would have a fraction of 1/1, the middle quarter would be 1/2, DV totals between 40 and 50 would go from 1/3 to 1/6, and finally the elite groups have unique fractions.

My concern is that this doesn't show a very large difference between more average stat spreads, and no difference at all for anything below that, making it only useful for comparing the good ones. I have an alternative, though. I also calculated percentiles for the distribution which give the more middling and common groups unique numbers. The DV totals 2-12 share the first percentile and 63-73 share the 99th, since a DV total in each of these ranges only happens 1% of the time. I think this is okay, as a 1/100 catch is good enough to be excited about and DVs are easily compared when they average 12 and higher.

I also noticed that the calculator accepts any HP stat as input, even if it isn't possible due to even/odd DVs. This may not be a very big issue, but it would be possible to sometimes calculate stats with better precision earlier if all information was used. Using percentiles would also work with a range of dvs. The estimation could just be reported as a range of percentiles. An average could also work, but I think a range is better. The max and min DV total can be calculated by first assuming HP to be highest/lowest, then adding the other DVs in making sure that they are properly even or odd.

Let me know what you think. I can explain more what I did on the math side and send you my data. I don't think it would be worth it for the program to do the calculations. Tell me what you are up for and what I can do to help. Thanks again for the cool program. Oh also Growlithe should be in the KO list for route 9.

 - Andy

**Comment by tewky** [comment]
Hi Andy

I forgot about this account... it's been a while since I've played any Pokemon.

Thanks for doing the calculations! I am very excited to see what you have, and I will do my best to integrate them with the DV Calculator.

You can contact me at anoble@protonmail.com or continue here.

Cheers

**Comment by tewky** [comment]
Sorry it took me so long to get to this - real life got in the way.

First up, I added Growlithe to Route 9. Secondly, although the HP stat doesn't have input validation, it is factored into accuracy calculations - i.e. if the HP DV and some other DVs are known, it eliminates other DVs that can't be possible with that HP DV.
Last but not least, I implemented a new rarity calculation based on your suggestion to improve the stat based on percentiles. The value still represents the % chance of finding an equivalent or better Pokemon (based on DVs, nothing else) but it's now based on a statistical distribution, so the rarity values seem much more realistic. I wrote some quick and dirty Python code this evening to calculate the DV distribution based on different sized groups, currently it's using a bucket size of 3 with 100,000 iterations to generate the rarity stats. Let me know what you think about this new method.

Python code:

```
import matplotlib.pyplot as plt
import numpy as np
import random
import math

step = 3
chunks = 75 // step

def group(results):
    grouped = [0 for i in range(chunks)]
    for chunk in np.arange(0, 75, step):
        total = 0
        for i in range(chunk, min(chunk + step, 74)):
            total += results[i]
        grouped[min(chunk // step, chunks - 1)] = total
    return grouped
    
def integrate(x, grouped):
    summed = [0 for i in range(chunks)]
    for i in range(0, chunks):
        total = 0
        for j in range(i, chunks):
            total += grouped[j]
        summed[i] = round(100.0 * (total / iterations), 2)
    return summed

iterations = 100000
results = [0 for i in range(75)]
for i in range(iterations):
    total = 0
    for stat in range(5):
        total += random.randint(0, 15)
    results[total - 1] += 1
    
x = np.arange(0, 75)
npresults = np.array(results)
y = npresults[x]

x2 = np.arange(0, chunks)
npgrouped = np.array(group(npresults))
y2 = integrate(x2, npgrouped)

#plt.plot(x, y)
plt.plot(x2, y2)
print(y2)
plt.show()

#[100.0, 100.0, 99.96, 99.79, 99.38, 98.44, 96.78, 93.88, 89.32, 82.87, 74.57, 64.7, 53.79, 42.49, 31.92, 22.46, 14.8, 9.11, 5.04, 2.54, 1.16, 0.42, 0.14, 0.02, 0.0]
```
